### ISSUE TITLE
[SPIKE] Inaccurate reports when nodes are using Policyfiles

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#163]
## Description
Currently, `chef-analyze` presents two reports to the users, a nodes report and
a cookbooks report. Both of these reports focus only on environments that are
running a very old version of Chef Client. The reports do not cover newer deployment
patterns like Policyfiles causing users to misunderstand the reports and actually,
causing confusion with the current state of their infrastructure.

Users that are in transition to migrate to the newer patterns, that is, users that have
both, old and new patterns will generate partial reports with inaccurate data.

Additionally, users on the latest patterns like Policyfiles and Effortless won't have any
benefit from using chef analyze.

## Chef Analyze Version
The latest version from `master`.

## Acceptance Criteria
* What is missing or inaccurate from the `chef analyze report` data?
* Why is that data inaccurate?
* File a new card that address the above bullet point and ensures `chef analyze report` works for nodes using Policyfiles
* Get backup from the Operations team that we can use to troubleshoot and reproduce this issue

**Comment by tyler-ball** [comment]
In our `nodesUsingCookbookVersion` function we use a search to query for "cookbooks_<name>_version:<version>". Using the same search in knife we get results, but we do not get results at the end of the report (all those cookbooks show as unused).

Next step is to interactively debug and see why our go code returns different results from our knife search.

The second issue we identified is that cookbooks included in policyfiles do not come back in the manage UI as available cookbooks. How does the chef client download those cookbooks? Are they stored somewhere in the chef server we are not looking, or does chef client download them from the origin instead of the chef server?

**Comment by mudash** [comment]
Further research revealed that:

- `/Cookbooks` end point on Chef Server API only returns Cookbooks that are _not_ uploaded with Policy files. Since we rely on this endpoint in `go-chef` library hence the report doesn't include the Policy file cookbooks. `Knife cookbook list` also uses the same end point and doesn't include the Policy file cookbooks. However `Knife search...` command queries the node indexes and pulls that information from the node attributes

- Discovered that `/Cookbook_artifacts` Chef Server API end point contains information about cookbooks uploaded via Policy files. Seems like we will have to implement that end point in `go-chef` library to retrieve this information. In addition modify the reporting functionality in chef-analyze to combine information retrieved from both `/Cookbooks` and `/Cookbook_artifacts` end points

**Comment by mudash** [comment]
Our Ops team have given us backup of Chef-Utility Org from hosted Chef. This org has bunch of nodes being managed by Policy files. Location of this has been shared in our team slack channel.

**Comment by mudash** [comment]
Added following cards for follow up work
https://app.zenhub.com/workspaces/chef-workstation-5c0aced04b5806bc2bfb9347/issues/chef/go-chef/19

https://app.zenhub.com/workspaces/chef-workstation-5c0aced04b5806bc2bfb9347/issues/chef/chef-analyze/231

**Comment by mudash** [comment]
Ops team confirmed in our weekly call, it is important to review reports before using capture.

**Comment by tyler-ball** [comment]
Thanks for the research and filing these cards @mudash!
