### ISSUE TITLE
Have appropriate environments to test this tool

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#22]
As a chef-analyze developer,
I need to have appropriate environments to test and develop chef-analyze,
So I can ensure that this tool will help real customers with real data and to cover all possible scenarios.

## Acceptance Criteria
- Ability to create ephemeral environments (able to be created and destroyed at will by engineers) to test against
- Environments should be able to be created from a customer backup
- By default, only the engineer who created an environment will have access to it
- Customer backups should be secured from access by any non-chef employee

## Implementation notes
Modify https://github.com/chef/chef-server/tree/master/terraform so others can consume these enhancements

**Comment by afiune** [comment]
FYI: this might be super useful. https://github.com/chef/chef-server/tree/master/terraform

**Comment by tyler-ball** [comment]
We need to ensure that our implementation does not leak secure information in any way

**Comment by tyler-ball** [comment]
This card is not wells scoped. We need to split it into (at least) two cards. The first one is that we need to expand the existing TF scripts to allow the upload of an existing backup.

The second one is creating some 'dummy' environments that closely mirror our real customer data but do not contain secure information, so we could check those backups into git (or a repo somewhere). Is this even possible? Customer environments are extremely complicated. Maybe instead we have cards that are 'collect backups that we can use from internal' so that all our test environments are actually real environments.

**Comment by tyler-ball** [comment]
Closed by https://github.com/chef/chef-server/pull/1891
