### ISSUE TITLE
Store reports to disk

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#82]
### Describe the Enhancement:
As a Chef analyze user,
I would like to be able to save the reports to disk as well as any error detail,
So that I can visualize the output of long reports as well as export and share them.

### Current Alternative
Run the commands and redirect the standard out and standard error to different files.
```
chef-analyze report nodes > nodes-report.out 2> nodes-report.err
```

### Can We Help You Implement This?:
N/A

**Comment by tyler-ball** [comment]
Implementation notes:

The report command will display the same information on STDOUT - a progress bar and a summary of report information (the current default behavior).

We will also save the report to the local folder that is a timestamped file (`123456.output.csv` or `12345.output.txt`) so users can see the detailed information they requested in a different context (because terminals are not good for trying to examine large files, text editors or CSV viewers are).

At the end of the summary we will output a message showing users what local files we created for them, so they can choose to delete them. Update the help text to show that the report command is going to output a summary in the terminal and a file on disk they can view at any later time.

We want to get user feedback on this behavior. It is not great to cause filesystem side effects without giving users a option to disable that.
