### ISSUE TITLE
Better handle timeouts

### ISSUE THREAD

**Issue by tas50** [chef/chef-analyze#87]
## Description
chef-analyze doesn't seem to timeout in a reasonable time or retry. I ran a report and I'm assuming that Hosted Chef is being slow to respond, but multiple minutes later I'm just stuck at 99%+. If the server hasn't responded we should fail after a short period of time and retry.

```
❰tsmith❙~/dev/work/chef-analyze(git✱≠tas50/specific_cops)❱✔≻ ./chef-analyze report cookbooks --detailed
Finding available cookbooks... (190 found)
Analyzing cookbooks...
189 / 190 [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->_] 99.47% 0 p/s
````

## Chef Analyze Version
Latest

## Platform Version
macOS Catalina

**Comment by afiune** [comment]
@tas50 is there a way to reproduce this behavior?

**Comment by tas50** [comment]
It's possible we could use some network testing toolkit to introduce failures, but outside of something like that it would be hard to reproduce. It did happen to me twice.

**Comment by afiune** [comment]
We need to investigate the reason for these hangs, our first assumption is that the problems
happen when the Chef Server is under a lot of stress and it can't complete, or it is too slow,
to resolve the X number of requests we launch from this tool. (Currently set to 50)

We need to have a mechanism to timeout requests so that they don't hang for a long time
and report back to the user that we couldn't complete some of them. (this inside the error
report/file)

We will also create a card to make the maximum number of simultaneous requests configurable.

**Comment by tas50** [comment]
Closing this out unless someone else reports it
