### ISSUE TITLE
Render table reports by calculating data to display

### ISSUE THREAD

**Issue by afiune** [chef/chef-analyze#93]
### Describe the Enhancement:

This is an idea to better render the table reports by calculating the data that
will be displayed, instead of hardcoding the column size. Once we retrieve the
data, we go over every line and calculate the maximum node name, CCR version
and operating system type. Then we use that max value per column.
 
### Describe the Need:

The data that we display for the nodes table report could be very different from each
user and therefore, hardcoding the header size is not the best way to display these reports.

### Current Alternative

The same, maximize the terminal window.

### Can We Help You Implement This?:

all yours @marcparadise 😉

**Comment by marcparadise** [comment]
Updating to allow the table package itself to handle column sizing, since it already does all those calculations as part of its rendering.  Earlier issues that prevented me from doing that got fixed when adjusting other table options.

All that's left is to try to find a way to detect when the report output has wrapped on the terminal, instead of displaying the 'expand your screen' message based on hard-coded size.
